### ISSUE TITLE
[studio] Get children API: none of the optional query arguments work

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4479]
## Describe the bug
None of the `excludes`, `sortStrategy`, `order`, `keyword`, `localeCode`  query arguments have any effect on the response.

## To Reproduce
1. Call the get children API without any optional arguments and observe response
2. Call again conjugating with the different query arguments
3. Arguments don't make a difference on the response

## Expected behavior
All arguments work, returning items coherent with the issued query. Both alone **and in combination**.

## Screenshots
{{If applicable, add screenshots to help explain your problem.}}

## Logs
```js
fetch('/studio/api/2/content/children_by_path.json?siteId=editorial-neue&path=/site/website/index.xml')
  .then(r => r.json())
  .then(r => r.children.map(i => i.label).join(', '))
  .then(console.log)
// => articles, Entertainment, Health, Search Results, Style, Technology

fetch('/studio/api/2/content/children_by_path.json?siteId=editorial-neue&path=/site/website/index.xml&excludes=/site/website/articles')
  .then(r => r.json())
  .then(r => r.children.map(i => i.label).join(', '))
  .then(console.log)
// => articles, Entertainment, Health, Search Results, Style, Technology

fetch('/studio/api/2/content/children_by_path.json?siteId=editorial-neue&path=/site/website/index.xml&excludes=/site/website/*.')
  .then(r => r.json())
  .then(r => r.children.map(i => i.label).join(', '))
  .then(console.log)
// => articles, Entertainment, Health, Search Results, Style, Technology

fetch('/studio/api/2/content/children_by_path.json?siteId=editorial-neue&path=/site/website/index.xml&order=ASC')
  .then(r => r.json())
  .then(r => r.children.map(i => i.label).join(', '))
  .then(console.log)
// => articles, Entertainment, Health, Search Results, Style, Technology

fetch('/studio/api/2/content/children_by_path.json?siteId=editorial-neue&path=/site/website/index.xml&order=DESC')
  .then(r => r.json())
  .then(r => r.children.map(i => i.label).join(', '))
  .then(console.log)
// => articles, Entertainment, Health, Search Results, Style, Technology

fetch('/studio/api/2/content/children_by_path.json?siteId=editorial-neue&path=/site/website/index.xml&order=desc')
  .then(r => r.json())
  .then(r => r.children.map(i => i.label).join(', '))
  .then(console.log)
// => articles, Entertainment, Health, Search Results, Style, Technology

fetch('/studio/api/2/content/children_by_path.json?siteId=editorial-neue&path=/site/website/index.xml&sortStrategy=alphabetical')
  .then(r => r.json())
  .then(r => r.children.map(i => i.label).join(', '))
  .then(console.log)
// => articles, Entertainment, Health, Search Results, Style, Technology

fetch('/studio/api/2/content/children_by_path.json?siteId=editorial-neue&path=/site/website/index.xml&keyword=articles')
  .then(r => r.json())
  .then(r => r.children.map(i => i.label).join(', '))
  .then(console.log)
// => articles, Entertainment, Health, Search Results, Style, Technology

fetch('/studio/api/2/content/children_by_path.json?siteId=editorial-neue&path=/site/website/index.xml&localeCode=fr')
  .then(r => r.json())
  .then(r => r.children.map(i => i.label).join(', '))
  .then(console.log)
// => articles, Entertainment, Health, Search Results, Style, Technology

fetch('/studio/api/2/content/children_by_path.json?siteId=editorial-neue&path=/site/website/index.xml&sortStrategy=default')
  .then(r => r.json())
  .then(r => r.children.map(i => i.label).join(', '))
  .then(console.log)
// => articles, Entertainment, Health, Search Results, Style, Technology

// etc...
```

### Version
4.0.0-SNAPSHOT

### OS
Mac OS

### Browser
Chrome

## Additional context
https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.1#/content/getChildrenByPath

**Comment by sumerjabri** [comment]
Excludes is actually not yet implemented, tracking in this ticket: https://github.com/craftercms/craftercms/issues/4352

**Comment by dejan-brkic** [comment]
@sumerjabri @rart DB schema is not equipped with infrastructure to perform a sort strategy. API sort strategy is based on XML content. We can do one of the following options
* give up on sort strategy and ordering until some future release
* implement based on API 1 sorting (XML content) and sacrifice performance
* fix DB schema to support sort strategies (sacrifice write performance)

**Comment by sumerjabri** [comment]
Decided to use Alphabetical as default with foldersFirst as the second option. Both can be supported without sacrificing performance. See updated docs:
https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.4#/content/getChildrenByPath

@rart you can try and see if foldersFirst makes sense in static-assets or similar. Most likely the Pages nav will use Alphabetical and other areas may be different. You'll need to experiment and let us know so we can meet with @russdanner and make final decisions.

**Comment by rart** [comment]
@dejan-brkic please clarify what was added. Was everything but sorting added now? The sorting that sumer described above, is it done?

**Comment by dejan-brkic** [comment]
Right now there is no sorting applied (nor order). Sorting will be added as Sumer described when PR is finalized.

**Comment by rart** [comment]
@dejan-brkic from your answer above, I understand that excludes, keyword & localeCode should now work.

Issues:

- `excludes` is no longer optional (i.e. 500s if `excludes` is not present on the request)
- `keyword` continues to do nothing
- `localeCode` continues to do nothing 
  - is this getting implemented or postponed?
    - how can we test this?

**Comment by dejan-brkic** [comment]
@rart 
Excludes are optional, it was a bug and it is fixed. Keyword and locale code are part of PR that needs to be merged.

PR:
https://github.com/craftercms/studio/pull/2411

**Comment by rart** [comment]
Verified `keyword` filter — FYI only exact matches (non-case-sensitive)

@sumerjabri `localeCode` excludes from the response the items that don't match that locale. I think we were going to return the source language item so that the UI can still show the full list and flag the untranslated ones via `item.localeCode !== currentlySelectedLocaleCode`?

**Comment by sumerjabri** [comment]
@rart @dejan-brkic 

Here is how the localeCode will work: When querying for a locale X, the backend will return all items of locale X + all items from the source locale that are not in locale X (items not translated yet).

**Comment by dejan-brkic** [comment]
@sumerjabri source locale is coming from? AFAIK it is not implemented

**Comment by sumerjabri** [comment]
@dejan-brkic Source Locale is configured in the Site as the default/main locale.
@jdrossl did we ever finalize that configuration? ^

**Comment by jdrossl** [comment]
@sumerjabri Studio is still unaware of translations, only Engine & Deployer were updated

**Comment by sumerjabri** [comment]
@rart please verify everything except localeCode which we will pursue in 4.1. You may close this ticket if it checks out.

**Comment by rart** [comment]
`order` in combination with `sortStrategy=foldersFirst` returns folders still first and reverse alphabetical items. Is that the right behaviour, @sumerjabri? Initially I was expecting `...&order=desc&sortStrategy=foldersFirst` to show folders last but not sure what the plan was.

A folders last (i.e. pages first?) strategy could be a good addition in the future btw.

**Comment by sumerjabri** [comment]
@rart this is behaving as expected. Thanks.

**Comment by rart** [comment]
Verified.

FYI: If you add 2 `excludes` arguments, one with a value and another without, it returns nothing at all. It's more or less a request syntax error so not sure we necessarily want to fix it, but thought I'd report it anyway. For example: `/studio/api/2/content/children_by_path?path=%2Fsite%2Fwebsite&siteId=editorial&order=desc&sortStrategy=foldersFirst&excludes=%2Fsite%2Fwebsite%2Farticles&excludes` returns an empty set of children.

On the contrary, `/studio/api/2/content/children_by_path?path=%2Fsite%2Fwebsite&siteId=editorial&order=desc&sortStrategy=foldersFirst&excludes` correctly ignores `excludes` and returns everything.

i.e. The backend shows resilience against 1 empty `excludes` on the request but for whatever reason, not two or more.
